USE [master]
GO

/****** Object:  Database [myDatabase]    Script Date: 5/21/2021 10:59:05 PM ******/
CREATE DATABASE [myDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'myDatabase_dat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\myDatabase.mdf' , SIZE = 10240KB , MAXSIZE = 51200KB , FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'myDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\myDatabase.ldf' , SIZE = 5120KB , MAXSIZE = 25600KB , FILEGROWTH = 5120KB )
GO

ALTER DATABASE [myDatabase] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [myDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [myDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [myDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [myDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [myDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [myDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [myDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [myDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [myDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [myDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [myDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [myDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [myDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [myDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [myDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [myDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [myDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [myDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [myDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [myDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [myDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [myDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [myDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [myDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [myDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [myDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [myDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [myDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [myDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [myDatabase] SET  READ_WRITE 
GO

